### ISSUE TITLE
style guide for documentation and coding conducts

### ISSUE THREAD

**Issue by quintonpryce** [guelph-code-ninjas/core#16]

**Comment by Blajda** [comment]
The code style used by Laravel
[PSR-1](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md)
[PSR-2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md)
[PSR-4](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-4-autoloader.md)

HTML and CSS guidelines used by Github
We should go over any additonal tools that we might use for CSS. (eg. sass)
[Primer Guidelines](http://primercss.io/guidelines/#scss)

**Comment by quintonpryce** [comment]
Referenced material for additional information: [PSR-0], [PSR-1], [PSR-2], [PSR-4].

[RFC 2119]: http://www.ietf.org/rfc/rfc2119.txt
[PSR-0]: https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-0.md
[PSR-1]: https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md
[PSR-2]: https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#4-classes-properties-and-methods
[PSR-4]: https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-4-autoloader.md

**Comment by quintonpryce** [comment]
Documentation style guide, Coding style guide, and coding standards.
