### ISSUE TITLE
implement a similarity check software

### ISSUE THREAD

**Issue by quintonpryce** [guelph-code-ninjas/core#33]
- [x] Store version with result (string, e.g. commit hash)
- [x] Change assignmentId to string
- [x] Send output to `/dev/null`
- [x] ~~Ignore `.git` directory~~ - checks are file extension based
- [x] Include result time

**Comment by ipavl** [comment]
[Early version](https://github.com/guelph-code-ninjas/core/wiki/Similarity-Checker-Setup)

**Comment by ipavl** [comment]
Still TODO:

- [ ] Store version with result (file hash)
- [ ] Change assignmentId to string
- [ ] Include date?

**Comment by ipavl** [comment]
MVP of [a wrapper](https://github.com/ipavl/similarity-api) is available, further features can be addressed in individual issues.
