### ISSUE TITLE
make a logo

### ISSUE THREAD

**Issue by judiMc** [guelph-code-ninjas/core#9]

**Comment by quintonpryce** [comment]
Virtual Assisted Teachings 
VAT

**Comment by quintonpryce** [comment]
Submission Assistant

**Comment by quintonpryce** [comment]
providing learners the right information at the right time.

**Comment by quintonpryce** [comment]
Providing students the right information at the right time.

**Comment by quintonpryce** [comment]
add the logo to the layout

**Comment by quintonpryce** [comment]
Computer graphic by <a href="http://www.flaticon.com/authors/freepik">Freepik</a> from <a href="http://www.flaticon.com/">Flaticon</a> is licensed under <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0">CC BY 3.0</a>. Made with <a href="http://logomakr.com" title="Logo Maker">Logo Maker</a>
![logomakr_8auve0](https://cloud.githubusercontent.com/assets/15935475/24591134/5f156a30-17c8-11e7-9305-79c309f3dcbe.png)
![logomakr_378yrc](https://cloud.githubusercontent.com/assets/15935475/24591135/5f169e00-17c8-11e7-99f8-5cf2b1a4726d.png)
